config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: {
    sessions: 'web/clients/sessions',
    registrations: 'web/clients/registrations'
  }
  devise_for :customers
  devise_for :users, path: '', path_names: {
    sign_in: 'api/erp/login',
    sign_out: 'api/erp/logout',
    registration: 'api/erp/signup',
  },
  controllers: {
    sessions: 'api/erp/users/sessions',
    registrations: 'api/erp/users/registrations',
    logout: 'api/erp/users/logout'
  },
  defaults: { format: :json }

  root to: 'web/home#index'
  get "/", to: "web/home#index"
  get 'busca', to: 'web/search#index', as: :search

  namespace :api, defaults: { format: :json }, constraints: { id: /\d+/ } do
    namespace :erp do
      resources :categories, only: %i[create show update destroy index]
      resources :subcategories, only: %i[create show update destroy index]
      resources :products, only: %i[index create show destroy update] do
        collection do
          resources :names, only: :index, module: :products
        end
      end

      resources :orders, only: %i[index create show destroy update] do
        collection do
          resources :status, only: :index, module: :orders
        end
      end
      resources :order_products, only: %i[create destroy update]

      namespace :reports do
        resources :average_ticket, only: :index
        resources :in_out, only: :index
        resources :summary, only: :index
      end

      resources :customers, only: %i[index create show destroy update] do
        collection do
          resources :names, only: :index, module: :customers
        end
      end

      resources :stock_histories, only: %i[index create destroy]
      resources :me, only: :index
    end
  end

  namespace :web do
    resources :cart_items, only: [:create, :index, :destroy, :update] do
      collection do
        resources :address, only: [:index, :new, :create], module: :cart_items
      end
    end

    resources :checkout, only: [:index, :create] do
      collection do
        resources :success, only: :index, module: :checkout
        resources :error, only: :index, module: :checkout
      end
    end

    resources :order_requests, only: [:index]
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/cart_item.rb
# == Schema Information
#
# Table name: cart_items
#
#  id         :integer          not null, primary key
#  quantity   :integer          default(1)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  client_id  :integer          not null
#  product_id :integer          not null
#
# Indexes
#
#  index_cart_items_on_client_id   (client_id)
#  index_cart_items_on_product_id  (product_id)
#
# Foreign Keys
#
#  client_id   (client_id => clients.id)
#  product_id  (product_id => products.id)
#
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :client

  validates :quantity, presence: true
  validates :quantity, numericality: { greater_than: 0 }

  def total_price
    product.price * quantity
  end
end

app/controllers/web/cart_items/address_controller.rb
class Web::CartItems::AddressController < Web::ApplicationController
  before_action :authenticate_client!

  def index
    @addresses = current_client.addresses
  end

  def new
    @address = current_client.addresses.new
  end

  def create
    @address = current_client.addresses.create!(address_params)

    flash[:notice] = "Endereço criado com sucesso"

    if params[:redirect_url].present?
      redirect_to params[:redirect_url]
    else
      redirect_to web_address_index_url
    end
  end

  private

  def address_params
    params.require(:address).permit(:street, :city, :state, :zip_code, :neighborhood, :number, :complement, :reference, :name)
  end
end

app/controllers/web/cart_items_controller.rb
class Web::CartItemsController < Web::ApplicationController
  before_action :authenticate_client!

  def index
    @cart_items = current_client.cart_items

    render "web/cart_items/index"
  end

  def destroy
    @cart_item = current_client.cart_items.find(params[:id])
    @cart_item.destroy
    redirect_back(fallback_location: root_path)
  end

  def update
    @cart_item = current_client.cart_items.find(params[:id])
    @cart_item.update(quantity: params[:quantity])
    redirect_back(fallback_location: root_path)
  end

  def create
    @cart_item = current_client.cart_items.find_or_initialize_by(product_id: params[:product_id])
    @cart_item.quantity = @cart_item.quantity.to_i + 1

    @cart_item.save!

    flash[:notice] = "Produto adicionado ao carrinho com sucesso!"
    redirect_back(fallback_location: root_path)
  rescue => e
    flash[:alert] = e.message
    redirect_back(fallback_location: root_path)
  end
end

app/views/web/cart_items/_aside.html.erb
 <aside>
  <h2>Resumo da compra</h2>

  <% cart_total = current_client.cart_items.sum { |item| item.quantity * item.product.price } %>

  <p>Total: <%= number_to_currency(cart_total, unit: "R$ ", separator: ",", delimiter: ".") %></p>

  <%= yield %>
</aside>

app/views/web/cart_items/index.html.erb
  <div class="cart-container">
    <h1>Carrinho de compras</h1>

    <div class="cart-container-content">
      <div class="cart-items">
        <% current_client.cart_items.each do |cart_item| %>
          <div class="cart-item">
            <%= image_tag cart_item.product.images.sample.url, class: "cart-item-image" %>

            <div class="cart-item-info">
              <%= cart_item.product.name %>

              <div class="cart-item-price">
                <%= number_to_currency(cart_item.product.price, unit: "R$ ", separator: ",", delimiter: ".") %>
              </div>
            </div>

            <div class="cart-item-quantity-controls">
              <%= form_with url: web_cart_item_path(cart_item), method: :put do |form| %>
                <%= form.hidden_field :quantity, value: cart_item.quantity - 1 %>
                <%= form.button "-", class: "cart-item-quantity-button" %>
              <% end %>

              <%= cart_item.quantity %>

              <%= form_with url: web_cart_item_path(cart_item), method: :put do |form| %>
                <%= form.hidden_field :quantity, value: cart_item.quantity + 1 %>
                <%= form.button "+", class: "cart-item-quantity-button" %>
              <% end %>
            </div>

            <%= form_with url: web_cart_item_path(cart_item), method: :delete do |form| %>
              <%= button_tag type: "submit", class: "cart-item-remove" do %>
                <%= icon("trash") %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>

      <%= render "web/cart_items/aside" do %>
        <%= link_to "Finalizar compra", web_address_index_path, class: "cart-item-checkout" %>
      <% end %>
    </div>
  </div>
</div>