config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: {
    sessions: 'web/clients/sessions',
    registrations: 'web/clients/registrations'
  }
  devise_for :customers
  devise_for :users, path: '', path_names: {
    sign_in: 'api/erp/login',
    sign_out: 'api/erp/logout',
    registration: 'api/erp/signup',
  },
  controllers: {
    sessions: 'api/erp/users/sessions',
    registrations: 'api/erp/users/registrations',
    logout: 'api/erp/users/logout'
  },
  defaults: { format: :json }

  root to: 'web/home#index'
  get "/", to: "web/home#index"
  get 'busca', to: 'web/search#index', as: :search

  namespace :api, defaults: { format: :json }, constraints: { id: /\d+/ } do
    namespace :erp do
      resources :categories, only: %i[create show update destroy index]
      resources :subcategories, only: %i[create show update destroy index]
      resources :products, only: %i[index create show destroy update] do
        collection do
          resources :names, only: :index, module: :products
        end
      end

      resources :orders, only: %i[index create show destroy update] do
        collection do
          resources :status, only: :index, module: :orders
        end
      end
      resources :order_products, only: %i[create destroy update]

      namespace :reports do
        resources :average_ticket, only: :index
        resources :in_out, only: :index
        resources :summary, only: :index
      end

      resources :customers, only: %i[index create show destroy update] do
        collection do
          resources :names, only: :index, module: :customers
        end
      end

      resources :stock_histories, only: %i[index create destroy]
      resources :me, only: :index
    end
  end

  namespace :web do
    resources :cart_items, only: [:create, :index, :destroy, :update] do
      collection do
        resources :address, only: [:index, :new, :create], module: :cart_items
      end
    end

    resources :checkout, only: [:index, :create] do
      collection do
        resources :success, only: :index, module: :checkout
        resources :error, only: :index, module: :checkout
      end
    end

    resources :order_requests, only: [:index]
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/cart_item.rb
# == Schema Information
#
# Table name: cart_items
#
#  id         :integer          not null, primary key
#  quantity   :integer          default(1)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  client_id  :integer          not null
#  product_id :integer          not null
#
# Indexes
#
#  index_cart_items_on_client_id   (client_id)
#  index_cart_items_on_product_id  (product_id)
#
# Foreign Keys
#
#  client_id   (client_id => clients.id)
#  product_id  (product_id => products.id)
#
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :client

  validates :quantity, presence: true
  validates :quantity, numericality: { greater_than: 0 }

  def total_price
    product.price * quantity
  end
end

app/controllers/web/cart_items/address_controller.rb
class Web::CartItems::AddressController < Web::ApplicationController
  before_action :authenticate_client!

  def index
    @addresses = current_client.addresses
  end

  def new
    @address = current_client.addresses.new
  end

  def create
    @address = current_client.addresses.create!(address_params)

    flash[:notice] = "Endereço criado com sucesso"

    if params[:redirect_url].present?
      redirect_to params[:redirect_url]
    else
      redirect_to web_address_index_url
    end
  end

  private

  def address_params
    params.require(:address).permit(:street, :city, :state, :zip_code, :neighborhood, :number, :complement, :reference, :name)
  end
end

app/controllers/web/cart_items_controller.rb
class Web::CartItemsController < Web::ApplicationController
  before_action :authenticate_client!

  def index
    @cart_items = current_client.cart_items

    render "web/cart_items/index"
  end

  def destroy
    @cart_item = current_client.cart_items.find(params[:id])
    @cart_item.destroy
    redirect_back(fallback_location: root_path)
  end

  def update
    @cart_item = current_client.cart_items.find(params[:id])
    @cart_item.update(quantity: params[:quantity])
    redirect_back(fallback_location: root_path)
  end

  def create
    @cart_item = current_client.cart_items.find_or_initialize_by(product_id: params[:product_id])
    @cart_item.quantity = @cart_item.quantity.to_i + 1

    @cart_item.save!

    flash[:notice] = "Produto adicionado ao carrinho com sucesso!"
    redirect_back(fallback_location: root_path)
  rescue => e
    flash[:alert] = e.message
    redirect_back(fallback_location: root_path)
  end
end

app/views/web/cart_items/address/_address.html.erb
<div class="address">
  <% current_client.addresses.each do |address| %>
    <div class="address-item">
      <%= radio_button_tag 'address_id', address.id %>
      <div class="address-details">
        <strong><%= address.name %></strong>

        <p class="address-details-street"><%= address.street %>, <%= address.number %> - <%= address.neighborhood %></p>
        <p class="address-details-city"><%= address.city %> / <%= address.state %></p>
        <p class="address-details-zip-code">CEP: <%= address.zip_code %></p>
      </div>
    </div>
  <% end %>

  <%= link_to "Adicionar novo endereço", new_web_address_path(redirect_url: web_address_index_url), class: "add-address-button" %>
</div>

app/views/web/cart_items/address/index.html.erb
<div class="cart-container">
  <h1>Selecione o endereço de entrega</h1>

  <%= form_tag web_checkout_index_path, method: :get, class: "cart-container-content" do %>
    <div class="cart-items">
      <%= render "web/cart_items/address/address" %>
    </div>

    <%= render "web/cart_items/aside" do %>
      <%= submit_tag "Finalizar compra", class: "cart-item-checkout" %>
    <% end %>
  <% end %>
</div>

app/views/web/cart_items/address/new.html.erb
<div class="address-form">
  <%= form_with model: @address, url: web_address_index_path do |form| %>
    <%= form.text_field :name, placeholder: "Nome" %>
    <%= form.text_field :street, placeholder: "Endereço" %>
    <%= form.text_field :city, placeholder: "Cidade" %>
    <%= form.text_field :state, placeholder: "Estado" %>
    <%= form.text_field :zip_code, placeholder: "CEP" %>
    <%= form.text_field :neighborhood, placeholder: "Bairro" %>
    <%= form.text_field :number, placeholder: "Número" %>
    <%= form.text_field :complement, placeholder: "Complemento" %>
    <%= form.text_field :reference, placeholder: "Referência" %>

    <%= form.submit "Salvar" %>
  <% end %>
</div>